### ISSUE TITLE
how to implement a component of overlap 

### ISSUE THREAD

**Issue by zhengying** [wolf81/composer#1]
So good project, thanks for your outstanding work.

I have a problem here:
example,  a dialog have a panel with a background color,  a textView and two button on it. 
but, I  can't make a component overlap, so how to implement the panel?

**Comment by wolf81** [comment]
In order to overlap, right now you'd need to make 2 different layouts. One layout for the background, another for the dialog. Your scene would then be responsible for showing the layouts on top of each other.

This is actually the approach that I will use for the game I am working on, but right now I am not yet busy with this part. 

I hope in the future to fix a few issues with the library and add some more examples and when I get to it, will also add an example for overlapping views. Sadly, right now I have to spend some time on other tasks, so please be patient with me :)

**Comment by wolf81** [comment]
By the way, I am also working on some widgets that I might eventually release as a separate library that could be used together with Composer. 

In this video (sorry in Dutch) you can see the menu that is arranged using the composer library and in the main game the bottom bar, status info, etc... I use all custom widgets here. 

In the future, when the user presses some bottom menu buttons, I will need to show e.g. inventory, so in that case I would need to overlay another layout as well.

https://www.youtube.com/watch?v=RutsB40DmhY

**Comment by zhengying** [comment]
thanks, I got it, I found it simple and intuition， use two layouts parallel in Border （I use a label as background panel）
Very interesting project, looking forward to your updates
```
Border(Margin(5, 5, 20, 0),{
    VStack(Stretch(0, 0), {
        Label("", MinSize(400,200), Stretch(0,0), ID("background")),
        FlexibleSpace(),
    }),
   VStack(Stretch(0, 0), {
		HStack(Stretch(0, 0), {
			ImageButton("up.png", MinSize(26), Stretch(0), ID('Close')),
            Label("Hello", MinSize(60, 26), Stretch(0), ID("text")),
		}),
        TextView("this is test view for test", MinSize(400,200), Stretch(0,0), ID("testview1")),
        FlexibleSpace(),
    }),
})

```
<img width="406" alt="Screen Shot 2022-03-08 at 9 18 05 AM" src="https://user-images.githubusercontent.com/1042545/157146852-a305b960-84cc-4607-8bd0-7abec5a46578.png">

Screen Shot 2022-03-08 at 9.18.05 AM
